### ISSUE TITLE
Screen sharing NOT working using FireFox 42 & 43

### ISSUE THREAD

**Issue by loganathan-r** [ging/licode#396]
Tried with Licode screen sharing demo room https://chotis2.dit.upm.es/room?id=52949272f4094e6e6c00001e using FireFox extension here https://github.com/ging/licode/tree/master/erizo_controller/erizoClient/extras/firefox-extension

but it was working with Firefox 41 and other lower versions.

**Comment by nachoaguadoc** [comment]
Hi, it should be working now. Thanks for the warning!

**Comment by loganathan-r** [comment]
Thanks, Does it involve any fix? or any config changes required? since still experiencing the problem at our Licode environment

**Comment by nachoaguadoc** [comment]
In our case it was failing because Licode wasn't properly updated. Are you using the last version of the project?

**Comment by loganathan-r** [comment]
No, I'll update to recent version and confirm. Thanks
