### ISSUE TITLE
InitLicode Bug

### ISSUE THREAD

**Issue by Vidmeet1** [ging/licode#571]
Hi all,
i once had licode running on an Ubuntu 14.04.
Now I set up a new clean system. Following the installation instructions I get the following output when running initLicode.sh:
12328
12341
2016-10-21 00:18:23.097  - ERROR: RPC - message: AMQP connection error killing process, errorMsg: 
[licode] Done, run basic_example/basicServer.js
root@h2623767:~/licode# 2016-10-21 00:18:27.809  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: 34f6cd59-cc7f-583f-414a-b0952d0e258b
[erizo-34f6cd59-cc7f-583f-414a-b0952d0e258b] 2016-10-21 00:18:28.072  - INFO: ErizoJS - message: Started, erizoId: 34f6cd59-cc7f-583f-414a-b0952d0e258b
2016-10-21 00:18:33.020  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 5
2016-10-21 00:18:41.029  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 4
2016-10-21 00:18:49.031  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 3
2016-10-21 00:18:57.035  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 2
2016-10-21 00:19:05.040  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 1
2016-10-21 00:19:08.039  - ERROR: ErizoController - message: addECtoCloudHandler cloudHandler does not respond - fatal

The nuve process seems to be killed immediately. Any suggestions?

**Comment by jcague** [comment]
there's a known issue that's going to be resolved by #569

**Comment by lodoyun** [comment]
Merged the PR, should be fixed now.
Feel free to reopen if it isn't :)

**Comment by shahnawaz-mm** [comment]
@lodoyun Still getting same error when execute initLicode.sh.

Please logs below:

root@ubuntu:/home/user/licode/scripts# ./initLicode.sh 
1203
1208
[licode] Done, run basic_example/basicServer.js
root@ubuntu:/home/user/licode/scripts# 2016-11-08 23:15:30.056  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: 2b50d31d-5512-5e8d-6cec-4c6a7441ef1d
[erizo-2b50d31d-5512-5e8d-6cec-4c6a7441ef1d] 2016-11-08 23:15:31.230  - INFO: ErizoJS - message: Started, erizoId: 2b50d31d-5512-5e8d-6cec-4c6a7441ef1d
2016-11-08 23:15:35.843  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 5
2016-11-08 23:15:43.854  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 4
2016-11-08 23:15:51.860  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 3
2016-11-08 23:15:59.877  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 2
2016-11-08 23:16:07.884  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 1
2016-11-08 23:16:10.884  - ERROR: ErizoController - message: addECtoCloudHandler cloudHandler does not respond - fatal
